### ISSUE TITLE
Sanitize first name in welcome message

### ISSUE THREAD

**Issue by jacklul** [php-telegram-bot/support-bot#11]
It seems like `htmlentities` is breaking for some people's names, maybe `filter_var($new_user->getFirstName(), FILTER_SANITIZE_SPECIAL_CHARS)` would be better? Anyone with experience in this?

**Comment by Hitmare** [comment]
What do you mean with `breaking people's names` ?

**Comment by jacklul** [comment]
Per telegram documentation only those characters are supported as HTML codes: " < > &

Currently `htmlentities` converts all HTML characters to their html `&xx;` code which makes some people's names broken.

**Comment by noplanman** [comment]
@jacklul Do you mean breaking like this?
![welcome-message-name](https://user-images.githubusercontent.com/9423417/36242514-5b5eed5c-1214-11e8-9586-fa09ed229a4c.png)

I was wondering if we even need to do any encoding.

e.g. This name of special characters: `©®åß∂ƒ@ªº∆¬`
without encoding: `©®åß∂ƒ@ªº∆¬`
`htmlentities()`: `&copy;&reg;&aring;&szlig;&part;&fnof;@&ordf;&ordm;∆&not;`

It seems Telegram itself handles HTML code inside the name.

**Comment by jacklul** [comment]
Exactly this, I don't think we need to encode other symbols than " < > & since only those are potential string breakers, right?

**Comment by noplanman** [comment]
Closing this off for now...
If some other issue pops up, we can reopen.
