### ISSUE TITLE
Prevent welcome message flood

### ISSUE THREAD

**Issue by noplanman** [php-telegram-bot/support-bot#16]
Instead of just sending a welcome message each time a user joins, best only send one if the previous message wasn't already a welcome message.
Or, maybe just a much shorter one?

Also, we could delete the "User joined the group" status message.

What do you guys think?

@php-telegram-bot/developers @Hitmare @chuv1

**Comment by chuv1** [comment]
I'm using a bit different approach in my bots - I store last send welcome message id in custom 'cleaner' table, and use it to delete old welcome message when new one is sent.

In `NewchatmembersCommand.php`:



```php
public function execute(){

	...

	$sent = Request::sendMessage($data);

	if($sent->isOk()){
			
		$this->removeOldWelcomes($sent->getResult());

	}

}

private function removeOldWelcomes($last_welcome){

	$last_welcome_id = $last_welcome->getMessageId();
	$chat_id = $last_welcome->getChat()->getId();

	if($last_welcome_id && $chat_id){

		$pdo = DB::getPdo();

		$old_welcome_id_query = "SELECT `message_id` FROM `cleaner` WHERE chat_id = {$chat_id}";

		$old_welcome_id = $pdo->query($old_welcome_id_query)->fetch();

		$last_welcome_save_query = "INSERT INTO `cleaner` VALUES ({$chat_id},{$last_welcome_id}) ON DUPLICATE KEY UPDATE `message_id` = {$last_welcome_id}";

		$pdo->exec($last_welcome_save_query);

		if(!empty($old_welcome_id) && !empty($old_welcome_id['message_id'])){
			$return = Request::deleteMessage([
				'chat_id'    => $chat_id,
				'message_id' => $old_welcome_id['message_id']
			]);
		};
	}

	return $return ?? false;

}
```

**Comment by noplanman** [comment]
@chuv1 What a great solution!

I think it's about time to have a sharper look at implementing simple options/configs (https://github.com/php-telegram-bot/core/issues/441) and simply save the welcome message id(s) like that.
