### ISSUE TITLE
Approval Survey for new Users 

### ISSUE THREAD

**Issue by Hitmare** [php-telegram-bot/support-bot#19]
I'll start this issue to collect and discuss ideas for a Approval Survey for new Users , so we can sort out some  of the non bot library questions

**Comment by noplanman** [comment]
As this has become real now, let's see how we can fix this.

I thought it would be easiest, if the welcome message when joining the group would include a link to the rules that would open a conversation with the bot. Then the rules would be displayed with an inline keyboard button "Agree" that needs to be clicked to activate the access and set permissions.

Flow would be something like this:
- User joins (has no permissions)
- User clicks "Read Rules" link
- Chat with bot opens and displays rules
- User reads the rules and agrees
- User clicks "Agree" inline keyboard button
- Permissions in the support group get set

@php-telegram-bot/developers What do you think about this, in terms of usability/simplicity and keeping bots away?

**Comment by Hitmare** [comment]
Well there should be a clean up function as well. 
Like when the User didn't agreed to the Rules he gets kicked (not banned) from the Group after like 30mins / 1 hour.

Sorry for the quite late response ^^

**Comment by noplanman** [comment]
No worries @Hitmare, been super busy with other stuff myself and haven't looked into this yet 😓 

I totally agree with your suggestion! Have added it to the flow in my initial comment.

**Comment by noplanman** [comment]
Will close here for now, as I've just deployed the new version which requires users to accept the rules before being granted permissions to post to the support group.
