### ISSUE TITLE
Welcome messages not getting deleted

### ISSUE THREAD

**Issue by noplanman** [php-telegram-bot/support-bot#20]
Seems like the welcome message deletion isn't working properly.

Probably makes sense to keep an array of welcome message IDs, in case a deletion doesn't work for whatever reason. Then every new member joining would trigger the deletion of all IDs in the array.

**Comment by Hitmare** [comment]
it should save the Welcome Message id's , delete them and check again if they are still exitst. If they are , for whatever reason, still exits, delete them again otherwise delete the id from the array

**Comment by noplanman** [comment]
Yes, at the moment it only saves 1 ID, deleting it before posting the new message.
I'm not sure what happened that it's suddenly not working correctly any more.

It's been working flawlessy until a few weeks ago :confused: 

Maybe Telegram doing API updates or something...

**Comment by noplanman** [comment]
@Hitmare I'll take care of this issue :+1:

**Comment by noplanman** [comment]
Has been fixed in develop branch.
