### ISSUE TITLE
Unban me group

### ISSUE THREAD

**Issue by nullcookies** [php-telegram-bot/support-bot#38]
Unban me group in telegram @PHP_Telegram_Bot_Support

**Comment by jacklul** [comment]
There must be a good reason why you got banned.
Also you didn't even care to give use your @username, we are not wizards.

**Comment by nullcookies** [comment]
> There must be a good reason why you got banned.
> Also you didn't even care to give use your @username, we are not wizards.

Asked a question about make poll in telegram 
my username in telegram @daprdev

**Comment by jacklul** [comment]
You're not on the banlist.
You might've been banned by Telegram itself for spamming.

**Comment by nullcookies** [comment]
> You're were banned by bot for not completing captcha.
> You will have one more try.

thanks for the unban
