### ISSUE TITLE
auto-kick other bots

### ISSUE THREAD

**Issue by lichtscheu** [php-telegram-bot/support-bot#4]
We shouldn't allow other bots in support-channel, therefore wer should auto-kick every joining user with bot in username. Before kick we could send a message in channel that bots are not allowed, if someone really has bot in name but isn't a bot, we could send some username to the user like "if you aren't a bot, write @userXY to get unbanned.

so we need a command to add the user to whitelist =)

**Comment by Hitmare** [comment]
bots have a value in their User data which can be used for checking if it is a bot or not so name matching isn't nessesary
