### ISSUE TITLE
Request Env Example

### ISSUE THREAD

**Issue by reactmore** [php-telegram-bot/support-bot#48]
hi can share new example dot env file ?  

i cant use env example on this repository because cannot read variable on .env file

PHP file
```php
require_once __DIR__ . '/vendor/autoload.php';
Dotenv::createUnsafeImmutable(__DIR__)->load();

$logging_paths['LOG_DIR'] = getenv('TG_LOGS_DIR');

print_r($logging_paths);
```

Response 
array(1) { ["LOG_DIR"]=> string(19) "${TG_BASE_DIR}/logs" }

**Comment by noplanman** [comment]
What does your `.env` file look like?

**Comment by reactmore** [comment]
TG_BASE_DIR='/laragon/www/bot'
TG_CACHE_DIR='${TG_BASE_DIR}/cache'
TG_COMMANDS_DIR='${TG_BASE_DIR}/commands'
TG_LOGS_DIR='${TG_BASE_DIR}/logs'
TG_PUBLIC_DIR='${TG_BASE_DIR}/public'

TG_LOGGING='{"error": "${TG_LOGS_DIR}/error.log", "update": "${TG_LOGS_DIR}/update.log"}'

I need change to double quote like this ? 

TG_LOGGING="{"error": "${TG_LOGS_DIR}/error.log", "update": "${TG_LOGS_DIR}/update.log"}"

**Comment by noplanman** [comment]
Yes, you will need to double-quote the above entries also and escape the double quotes within the strings that have JSON:
```
TG_BASE_DIR="/laragon/www/bot"
TG_CACHE_DIR="${TG_BASE_DIR}/cache"
TG_COMMANDS_DIR="${TG_BASE_DIR}/commands"
TG_LOGS_DIR="${TG_BASE_DIR}/logs"
TG_PUBLIC_DIR="${TG_BASE_DIR}/public"

TG_LOGGING="{\"error\": \"${TG_LOGS_DIR}/error.log\", \"update\": \"${TG_LOGS_DIR}/update.log\"}"
```

**Comment by reactmore** [comment]
Cool, thanks for help @noplanman
